//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInfo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public double BasicSalary { get; set; }
    }
}
